<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [2]:
x = 10

In [12]:
assert x >= 0, "x is becoming negative!"

In [4]:
y = -1

In [11]:
assert y >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [14]:
number = input("Give me a number and I will calculate its square.")
square = int(number) ** 2
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.99
The square of 99 is 9801!


In [117]:
try: 
    number = input("Give me a number and I will calculate its square.")
    square = int(number) ** 2
    print(f'The square of {number} is {square}!')
except: 
    print(f"Oh no! I cannot square {number}!")

Oh no! I cannot square abc!


In [4]:
try: 
    number = input("Give me a number and I will calculate its square.")
    square = int(number) ** 2
    print(f'The square of {number} is {square}!')
except: 
    print(f"Oh no! I cannot square {number}!")

Give me a number and I will calculate its square.abc
Oh no! I cannot square abc!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [14]:
def funny_add(a, b, c = 1):
    return a + 10 * b + 100 * c

In [10]:
funny_add(1, 2, 3)

321

In [12]:
funny_add(c = 3, b = 1, a = 2)

312

In [15]:
funny_add(1, 2)

121

In [17]:
funny_add(a = 1, b = 2)

121

In [18]:
funny_add(c = 3, b = 1, a = 2)

312

In [19]:
funny_add(1, c = 3, b = 2)

321

In [20]:
funny_add(1, b = 2)

121

In [21]:
funny_add(a = 2, 1)

SyntaxError: positional argument follows keyword argument (16213395.py, line 1)

### 2.2 Docstrings

In [22]:
def funny_add(a, b, c=1):
    '''
    
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work. 
    
    '''
    return a + 10 * b + 100 * c

In [23]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [25]:
import numpy as np

In [26]:
def my_function(angle, trig_function): 
    return trig_function(angle)

In [27]:
my_function(np.pi/2, np.sin)        #sin(pi/2)

1.0

In [28]:
my_function(np.pi/2, np.cos)       #cos(pi/2)

6.123233995736766e-17

In [29]:
my_function(np.pi/2, lambda x: np.cos(2*x))

-1.0

### 2.4 More unpacking

In [30]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [32]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [34]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [38]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)
print(*_)

1 5
2 3 4


## Exercise 1 :  A better calculator I

In [113]:
x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

In [40]:
def add(x, y):
    z = x + y
    return z
print(add(x, y))

[100 100 100 100 100]


In [41]:
def subtract(x, y): 
    z = x - y
    return z
print(subtract(x, y))

[-28 -32 -12  52 -46]


In [42]:
def multiply(x, y): 
    z = x * y
    return z
print(multiply(x, y))

[2304 2244 2464 1824 1971]


In [114]:
def divide(x, y): 
    assert np.all(y != 0), "Cannot be divided by zero!"
    return x / y
print(divide(x, y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [135]:
np.seterr(all='raise')    #to prevent numpy from returning infinity when divided by zero

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [143]:
x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

In [89]:
def add(x, y):
    z = x + y
    return z
print(add(x, y))

[100 100 100 100 100]


In [90]:
def subtract(x, y): 
    z = x - y
    return z
print(subtract(x, y))

[-28 -32 -12  52 -46]


In [146]:
def multiply(x, y): 
    z = x * y
    return z
print(multiply(x, y))

[2304 2244 2464 1824 1971]


In [144]:
def divide(x, y): 
    try: 
        return x / y
    except ZeroDivisionError:
        print("Cannot be divided by zero!")
    except FloatingPointError:
        print("Cannot be divided by zero!")
divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [148]:
z = np.array([0, 1, 2, 3, 4])    #just testing for fun. 
divide(x, z)

Cannot be divided by zero!
