<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name): 
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else: 
        return f'Hello {name}!'

In [3]:
greeting('Batman')

'Hello Batman! So, nice to meet you!'

In [4]:
greeting('Aqua Man')

'Hello Aqua Man!'

In [6]:
greet = greeting(name = 'Super Man')
print(greet)

Hello Super Man!


In [7]:
print(greeting(name = 'Super Man'))

Hello Super Man!


In [33]:
import numpy as np

numbers = [1, 2, 3, 4, 5]

np_numbers = np.array(numbers)

print(np_numbers)

[1 2 3 4 5]


In [34]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [38]:
list_min, list_max, list_mean = basic_stats(numbers)

print(basic_stats(numbers))

(1, 5, 3.0)


### 1.2 Named functions that don’t return

In [39]:
print() 

### 1.3 Anonymous functions

In [40]:
my_short_function = lambda name: f"Hello {name}!"

In [41]:
my_short_function(name = "Super Man")

'Hello Super Man!'

In [42]:
numbers = [[9, 0, 10],
          [8, 1, 11],
          [7, 2, 12],
          [6, 3, 13],
          [5, 4, 14],
          [4, 5, 15],
          [3, 6, 16],
          [2, 7, 17],
          [1, 8, 18],
          [0, 9, 19]]

In [45]:
sorted(numbers)

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [46]:
sorted(numbers, key = lambda x:x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [47]:
sorted(numbers, key = lambda x: sum(x))

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [48]:
def greeting(name = 'no one'): 
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else: 
        return f'Hello {name}!'

In [49]:
greeting()

'Hello no one!'

In [51]:
print('I', 'am', 'Batman!')

I am Batman!


In [52]:
print('I', 'am', 'Batman', sep = '---')

I---am---Batman


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [53]:
def greeting(name): 
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

In [55]:
greeting('Aqua Man')

'Hello Aqua Man!'

In [56]:
greeting('Batman')

'Hello Batman! So, nice to meet you!'

Reason: When name is not equal to 'Batman', the function will return false and jump to the next return line which is 'Hello {name}!' I fit is True, it will return the first line. 

## Exercise 2 :  Calculator functions

In [120]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [87]:
def add(x, y):
    z = x + y
    return z 
print(add(x, y))

[100 100 100 100 100]


In [90]:
def subtract(x, y):
    z = x - y
    return z
print(subtract(x, y))

[-28 -32 -12  52 -46]


In [91]:
def multiply(x, y):
    z = x * y
    return z
print(multiply(x, y))

[2304 2244 2464 1824 1971]


In [130]:
def divide(x, y): 
    y = np.array(y)
    if not np.any(y == 0):
        return x / y
    return "Cannot divide by zero!"

print(divide(x, y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [122]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [124]:
def max_info(numbers): 
    np_numbers = np.array(numbers)
    return np_numbers.max(), np_numbers.argmax()

print(max_info(numbers))

(83, 2)
