<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [8]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                 "Tony Stark": "Iron Man",
                 "Stephen Strange": "Doctor Strange"
                 }

superhero_info

{'Natasha Romanoff': 'Black Widow',
 'Tony Stark': 'Iron Man',
 'Stephen Strange': 'Doctor Strange'}

### 1.2 Accessing data from a list (or array)

In [12]:
print(py_real_names[0])

print(py_super_names[0])

print(py_super_names[2])

print(py_super_names[-1])

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [15]:
print(superhero_info["Natasha Romanoff"])

print(superhero_info.keys())

print(superhero_info.values())

Black Widow
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


### 1.4 Higher dimensional lists

In [18]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                    ['Tony Stark', 'Iron Man'],
                    ['Stephen Strange', 'Doctor Strange']]

py_superhero_info

[['Natasha Romanoff', 'Black Widow'],
 ['Tony Stark', 'Iron Man'],
 ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
             [5, "E"], [6, "F"], [7, "G"], [8, "H"],
             [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape)

10
10
(10, 2)


### 2.2 Arrays are fussy about type

In [28]:
py_list = [1, 1.5, 'A']

np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [35]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [36]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [37]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)


In [38]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [39]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [42]:
py_list * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [43]:
np_array * 2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [46]:
py_list ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [49]:
py_list == 3

False

In [50]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [51]:
np_array == 3

array([False, False,  True, False, False])

In [52]:
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [53]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [54]:
sum(py_list)

15

In [55]:
max(py_list)

5

In [56]:
min(py_list)

1

In [57]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [58]:
np_array.sum()

15

In [59]:
np_array.mean()

3.0

In [60]:
np_array.max()

5

In [61]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. Two similarities between lists and arrays 
    1. The indexing of variables in lists and arrays start from 0. 
    1. We can find the max, min, sum using lists and arrays (when the elements are numbers).


2. Two differences between lists and arrays 
    1. When added, lists add more elements into the list (by extending its length) instead of adding the values of the elements when they are numbers. 
    1. When multipled, lists repeat the elements (by extending the list) in the list instead of multiplying the value of the elements when they are numbers. 
*Squaring will not work in lists but works in arrays if the elements are numbers.
Asking questions is easier in arrays than lists because array checks every elements.
One prominent difference between lists and arrays is that arrays like having a single data type; lists are more accommodating.(Arrays tolerate only a single type.)*

3. What is a dictionary? 
   
   Dictionary contains names and the names can bring another value. 
   *Dictionaries hold data (values) paired with a key. i.e. you can access the value (in this case, the superhero name) using the real name as a key.*

## Exercise 2 :  Index me

In [72]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0], py_list[2], py_list[4], py_list[6], py_list[8])


a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [69]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

superhero_info

{'Natasha Romanoff': 'BLACK WIDOW',
 'Tony Stark': 'IRON MAN',
 'Stephen Strange': 'DOCTOR STRANGE'}

## Exercise 4 :  How many ones

In [66]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_numbers = np.array(numbers)

x = np_numbers == 1

x.sum()

9