<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
import numpy as np
py_list = ["a1", "b2", "c3", "d4", "e5",
           "f6", "g7", "h8", "i9", "j10"]

np_array = np.array(py_list)

In [14]:
x = py_list

In [11]:
x[0]

'a1'

In [12]:
x[-1]

'j10'

In [15]:
x[0:3]

['a1', 'b2', 'c3']

In [16]:
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [17]:
x[1:6:2]

['b2', 'd4', 'f6']

In [18]:
x[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [19]:
x[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [20]:
x[5:2:-1]

['f6', 'e5', 'd4']

In [21]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

### 1.2 Subsetting by masking (Arrays only)

In [22]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [23]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [24]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [26]:
np_array[(np_array > 3) & (np_array < 8)] 

array([4, 5, 6, 7])

In [27]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [28]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
             [5, "E"], [6, "F"], [7, "G"], [8, "H"],
             [9, "I"], [10, "J"]]

In [29]:
py_list_2d[3]

[4, 'D']

In [30]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [31]:
py_list_2d[:3][0]

[1, 'A']

In [34]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [35]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"], 
                       [5, "E"], [6, "F"], [7, "G"], [8, "H"], 
                       [9, "I"], [10, "J"]])

In [36]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [37]:
np_array_2d[3,0]

'4'

In [38]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [39]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [40]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [41]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [43]:
x = [1]*10
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [44]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
x

[1, 2, 3, 4]

In [45]:
x = [1]
x += [2]
x += [3]
x += [4]
x

[1, 2, 3, 4]

In [47]:
x = [1]
x += [2, 3, 4]
x

[1, 2, 3, 4]

In [48]:
x = [1]
x = [2, 3, 4] + x
x

[2, 3, 4, 1]

In [49]:
x = [1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [50]:
a = (1, 2, 3)

In [51]:
print(a[0])

1


In [52]:
a[0] = -1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [61]:
x = [1, 2, 3]
y = x
z = x

y += [4]
z += [5]
print(z)
print(y)
print(x)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [64]:
x = [1, 2, 3]

y = x.copy()
z = x.copy()

y += [4]
z += [4, 5]

print(x)
print(y)
print(z)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]


## Exercise 1 :  Total recall?

|**Term**|**Brief Description**|
|:-|:-:|
|Subsetting|Taking some elements through different ways: indexing, slicing, masking (*'select'*)|
|Indexing|Choosing the element (*selecting one element*)|
|Slicing|Picking a range of elements (*selecting a range of elements*)|
|Masking|Only picking elements that meet my criteria (*NumPy will show only those that are true*)|

## Exercise 2 :  Show me the ‘odd’ letters

In [68]:
np_array_2d = np.array ([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                       [5, "E"], [7, "G"], [6, "F"], [8, "H"], 
                       [10, "J"], [9, "I"]])

In [69]:
first = np_array_2d[:, 0]
first

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [77]:
x = first.astype(int)
x

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [79]:
y = x.copy()
z = y%2
z

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [83]:
mask_z = z == 1
mask_z

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [86]:
np_array_2d[mask_z]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')